apiVersion: v1
kind: Template
labels:
  template: prometheus-demoapp
metadata:
  annotations:
    description: prometheus demo application
    tags: instant-app
  name: demoapplication-builder

objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: prometheus-demoapp
  spec: {}
  status:
    dockerImageRepository: ""

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: prometheus-demoapp
    labels:
      name: prometheus-demoapp
      annotations:
        template.alpha.openshift.io/wait-for-ready: true
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: prometheus-demoapp:latest
    resources: {}
    source:
      contextDir: ${REPO_CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      type: Docker
    triggers:
    - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    name: prometheus-demoapp-service
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/scheme: http
  spec:
    ports:
      - name: web
        protocol: TCP
        port: 80
        targetPort: 5000
    selector:
      name: prometheus-demoapp
    sessionAffinity: None
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: Route
  metadata:
    name: prometheus-demoapp-route
  spec:
    to:
      kind: Service
      name: prometheus-demoapp-service
  status: {}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: prometheus-demoapp
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 120
    triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - prometheus-demoapp
          from:
            kind: ImageStreamTag
            name: prometheus-demoapp:latest
      - type: ConfigChange
    replicas: 2
    template:
      metadata:
        labels:
          name: prometheus-demoapp
      spec:
        containers:
          - name: prometheus-demoapp
            image: prometheus-demoapp
            ports:
              - containerPort: 5000
                protocol: TCP
            imagePullPolicy: IfNotPresent
        restartPolicy: Always

parameters:
- description: Git repository with Dockerfile
  displayName: Repository URL
  name: REPO_URL
  value: https://github.com/accorvin/prometheus-openshift-demo.git
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: REPO_CONTEXTDIR
  value: demoapplication
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: REPO_REF
  value: master

